#!/bin/ruby

# This is the config script for Kyu.
#
#  Tom Trebisky  1-6-2017
#

$targets = %w( bbb orange_pi )

def usage
    puts "Pick one of the following:"
    $targets.each { |t|
	puts "     " + t
    }
end

if ARGV.size != 1
    usage
    exit
end

target = ARGV[0]

unless $targets.include? target
    puts "I don't recognize that target"
    usage
    exit
end

system "make clean"

system "rm -f board"
system "ln -s #{target} board"

system "rm -f Makefile"
system "ln -s configs/Makefile.#{target} Makefile"

system "rm -f kyu.lds"
system "ln -s configs/#{target}.lds kyu.lds"

system "make clean"

# XXX when we again support the x86
# we will add galileo as a board
# AND we will need to make the "arch" link.

puts "Ready for " + target
