#!/bin/ruby

# This is the config script for Kyu.
#
#  Tom Trebisky  1-6-2017
#

$targets = %w( bbb orange_pi orange_pi64 fire3 )

def usage
    puts "Pick one of the following:"
    $targets.each { |t|
	puts "     " + t
    }
end

if ARGV.size != 1
    usage
    exit
end

target = ARGV[0]

unless $targets.include? target
    puts "I don't recognize that target"
    usage
    exit
end

# We must have a board directory or
# make clean goes into a nasty loop
system "rm -f board"
system "ln -s #{target} board"


system "make clean"

system "rm -f Makefile"
system "ln -s configs/Makefile.#{target} Makefile"

system "rm -f Makefile.inc"
system "ln -s configs/Makefile.inc.#{target} Makefile.inc"

system "rm -f kyu.lds"
system "ln -s configs/#{target}.lds kyu.lds"

system "make clean"

# XXX when we again support the x86
# we will add galileo as a board
# AND we will need to make the "arch" link
# in some target dependent way.

system "rm -f arch"

if target == "fire3"
    system "ln -s armv8 arch"
elsif target == "orange_pi64"
    system "ln -s armv8 arch"
else
    system "ln -s armv7 arch"
end


puts "Ready for " + target
