#!/usr/bin/perl

# Holy cow! A perl script!!
# usage: mkversion -ihexapod_version -v$(shell cat VERSION) >version.c
# ./mkversion -ikyu_version -v$(VERSION) >version.c

$ident = "kyu_version";
$vernum = "";
$board = "";

$user = `whoami`;
chomp $user;

$board = `readlink board`;
chomp $board;

$vernum = `cat VERSION`;
chomp $vernum;

# Command line arguments, -v and -i
while ( $_ = $ARGV[0] ) {
    last unless /^-/;
    shift;

    ($ident = $_) =~ s/^..// if /^-i/;
    ($vernum = $_) =~ s/^..// if /^-v/;
}

$ident = "kyu_version" if ( $ident eq "" );
$vernum = "0.0" if ( $vernum eq "" );
$board = "VME" if ( $board eq "" );

$date = `date`;
chomp $date;

print <<EOF;
/* version.c
 */

EOF

print "char \*$ident";
print " = \"version $vernum for $board, Compiled by $user: $date\"\;\n";

print <<EOF;

/* THE END */
EOF
