#!/bin/ruby

$files = %w{
linux/module.h
linux/i2c.h
linux/err.h

linux/device.h
linux/slab.h
linux/of.h

linux/interrupt.h
linux/completion.h
linux/gpio.h
}

$files2 = <<END
linux/list.h
linux/types.h
uapi/linux/types.h
END

$src = "/u1/BBB/linux-4.0.5/include"
$dst = "../include"

def copy_list ( list )
    list.each { |f|
	fs = $src + "/" + f
	dd = $dst + "/linux"
	cmd = "cp #{fs} #{dd}"

	system cmd
    }
end

def run_list ( text )
    list = text.split "\n"
    list.each { |line|
	puts line
	path = line.split "/"
	fs = $src + "/" + line
	f = path.pop
	if ( path.length == 0 )
	    puts "?? direct copy"
	    dd = $dst
	    cmd = "cp #{fs} #{dd}"
	    system cmd
	else
	    dir = $dst
	    path.each { |e|
		dir = dir + "/" + e
		puts "check: #{dir}"
		unless FileTest.directory? dir
		    puts "making directory: #{dir}"
		    Dir.mkdir dir
		end
	    }
	    dd = dir + "/" + f
	    cmd = "cp #{fs} #{dd}"
	    system cmd
	end

    }
end

def mk_list ( text )
    return text.split "\n"
end

# copy_list $files
#copy_list ( mk_list $files2 )
run_list $files2

# THE END
